name: Build and Push Docker Images
on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - '.github/workflows/build-release.yaml'
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tf:
          - 0.12.26
          - 0.12.28
        alks:
          - 1.3.2
          - 1.3.4
          - 1.4.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Push
        uses: docker/build-push-action@v1.1.0
        with:
          repository: dkolb/terraform-alks
          username: dkolb
          password: ${{ secrets.DOCKER_TOKEN }}
          tags: tf-${{ matrix.tf }}_alks-${{ matrix.alks }}
          build_args: TERRAFORM_VERSION=${{ matrix.tf }},ALKS_VERSION=${{ matrix.alks }}
          add_git_labels: true
